# Generated by Django 3.2.7 on 2021-09-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freightcar',
            name='cargo_amount',
            field=models.FloatField(),
        ),
    ]
